spring:
  cloud:
    config:
      discovery:
        enabled: true
  jackson:
    serialization:
      indent_output: true
  data:
    mongodb:
      uri: mongodb://localhost/properties-service

server:
  port: 8888
