server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            profile: local
            server:
                default-label: latest
                default-profile: production
                jdbc:
                    order: 0
                    sql: SELECT `key`, `value` FROM `properties` WHERE `application`=? AND `profile`=? AND `label`=?;
        refresh:
            enabled: false
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
            connection-timeout: 5000
            maximum-pool-size: 10
        password: root
        platform: mysql
        url: jdbc:mariadb://localhost:3306/properties-service?createDatabaseIfNotExist=true
        username: root
    jackson:
        serialization:
            indent_output: true
    profiles:
        active: jdbc
